before_script:
  # load the requested modules on oberon
  - module load anaconda/3 espeak/1.49.2 festival/2.4

phonemizer-build:
  stage: build
  script:
    # create a Python virtual environment dedicated to the test (if not existing)
    - conda create --name phonemizer-ci python=3 2> /dev/null || true
    - conda activate phonemizer-ci

    # install the phonemizer
    - pip install coverage
    - python setup.py build
    - python setup.py install

phonemizer-test:
  stage: test
  script:
    # run the unit tests within the CI environment
    - conda activate phonemizer-ci
    - python setup.py test

phonemizer-oberon:
  # install phonemizer in the "wordseg" virtual environment on oberon (users just
  # have to type "conda activate wordseg" to use it)
  stage: deploy
  script:
    - conda activate wordseg
    - cd /shared/apps/phonemizer
    - git pull origin master
    - python setup.py install

phonemizer-pypi:
  # upload the release on PyPI
  stage: deploy
  variables:
    TWINE_USERNAME: $PYPI_USERNAME
    TWINE_PASSWORD: $PYPI_PASSWORD
  script:
    - conda activate phonemizer-ci
    - pip install twine
    - rm -rf dist
    - python setup.py sdist
    - twine upload dist/*
  only:
    - tags
