dist: bionic
language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"

# no need of git history
git:
  depth: 1

# test only the master branch
branches:
  only:
    - master

before_install:
  - sudo apt-get update
  - sudo apt-get -y install festival festvox-us1 festlex-cmu festlex-poslex espeak-ng mbrola mbrola-fr1

install:
  - pip install --upgrade pip
  - python setup.py install
  - pip install --upgrade pytest coverage codecov

script:
  - phonemize --version
  - pytest

after_success:
  - coverage run
  - codecov

cache:
  - pip

notifications:
  email: false
